### ISSUE TITLE
Issue gain access to admin as described in http://mongolar.org/demo

### ISSUE THREAD

**Issue by sathish331977** [mongolar/mongolardemo#1]
Issue gain access to admin as described in http://mongolar.org/demo

**Comment by jasonrichardsmith** [comment]
Thank you for signing up for the Mongolar Demo.

You have now been granted admin privileges.

I ask that you do not tamper with the existing paths.  They are only there for reference.

To view the available templates please visit this folder.
https://github.com/mongolar/mongolardemo/tree/master/assets/templates

You will need to type in the template file name, but only relative to the templates folder path.  I am working on a system to read comments to make templates available as a selection.

After clicking on Content on the [admin page](http://demo.mongolar.org/admin) you can add a new path, by clicking "Add Path."

All content gets reset at 50 past the hour.

@sathish331977
